site_name: Custom data format
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Setup: setup.md
  - File types: filetype.md
  - Kaitai basics: kaitai_basics.md
  - Construct basics: construct_basics.md
  - Putting it together: putting_it_together.md
  - Conclusion: conclusion.md
  - Advanced: advanced.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js