site_name: Custom data format
nav:
  - Home: 00_index.md
  - 1. Introduction: 01_introduction.md
  - 2. Setup: 02_setup.md
  - 3. File types: 03_filetype.md
  - 4. Kaitai basics: 04_kaitai_basics.md
  - 5. Construct basics: 05_construct_basics.md
  - 6. Creating Example Data: 06_creating_example_data.md
  - 7. Kaitai Next Steps: 07_kaitai_next_steps.md
  - 8. Construct Next Steps: 08_construct_next_steps.md
  - 9. Conclusion: 09_conclusion.md
  - Appendix: 10_appendix.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js