site_name: Custom data format
nav:
  - Introduction: index.md
  - Setup: 01_setup.md
  - File types: 02_filetype.md
  - Kaitai basics: 03_kaitai_basics.md
  - Construct basics: 04_construct_basics.md
  - Creating Example Data: 05_creating_example_data.md
  - Kaitai Next Steps: 06_kaitai_next_steps.md
  - Construct Next Steps: 07_construct_next_steps.md
  - Conclusion: 08_conclusion.md
  - Appendix: 09_appendix.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js