site_name: Custom data format
nav:
  - Home: index.md
  - 1. Introduction: introduction.md
  - 2. Setup: setup.md
  - 3. File types: filetype.md
  - 4. Kaitai basics: kaitai_basics.md
  - 5. Construct basics: construct_basics.md
  - 6. Creating Example Data: creating_example_data.md
  - 7. Kaitai Next Steps: kaitai_next_steps.md
  - 8. Construct Next Steps: construct_next_steps.md
  - 9. Conclusion: conclusion.md
  - Appendix: appendix.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js