site_name: Custom data format
nav:
  - Introduction: index.md
  - Setup: 01_setup.md
  - File types: 02_files.md
  - Computer Representation: 03_representation.md
  - Kaitai basics: 04_kaitai_basics.md
  - Construct basics: 05_construct_basics.md
  - Creating Example Data: 06_creating_example_data.md
  - Kaitai Next Steps: 07_kaitai_next_steps.md
  - Construct Next Steps: 08_construct_next_steps.md
  - Conclusion: 09_conclusion.md
  - Appendix: 10_appendix.md
theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js